// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &ProjectRateLimitsDataSource{}

func NewProjectRateLimitsDataSource() datasource.DataSource {
	return &ProjectRateLimitsDataSource{}
}

type ProjectRateLimitsDataSource struct {
	baseDataSource
}

func (d *ProjectRateLimitsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_rate_limits"
}

func (d *ProjectRateLimitsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Returns the rate limits per model for a project.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"rate_limits": schema.SetNestedAttribute{
				MarkdownDescription: "List of rate limits.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[ProjectRateLimitsDataSourceModelRateLimitsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "The rate limit identifier.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"model": schema.StringAttribute{
							MarkdownDescription: "The model this rate limit applies to.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"max_requests_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum requests per minute.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_tokens_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum tokens per minute.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_images_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum images per minute. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_audio_megabytes_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum audio megabytes per minute. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_requests_per_1_day": schema.Int64Attribute{
							MarkdownDescription: "The maximum requests per day. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"batch_1_day_max_input_tokens": schema.Int64Attribute{
							MarkdownDescription: "The maximum batch input tokens per day. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *ProjectRateLimitsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectRateLimitsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.ProjectRateLimit
	params := &apiclient.ListProjectRateLimitsParams{
		Limit: ptr.Ptr(int64(100)),
	}

done:
	for {

		httpResp, err := d.client.ListProjectRateLimitsWithResponse(ctx, data.ProjectId.ValueString(), params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code: %d", httpResp.StatusCode()))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		switch v := any(httpResp.JSON200.HasMore).(type) {
		case bool:
			if !v {
				break done
			}
		case *bool:
			if v == nil || !*v {
				break done
			}
		default:
			panic("unknown type")
		}

		switch v := any(httpResp.JSON200.LastId).(type) {
		case string:
			params.After = &v
		case *string:
			if v == nil {
				params.After = nil
			} else {
				params.After = v
			}
		default:
			panic("unknown type")
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectRateLimitsDataSourceModel struct {
	ProjectId  supertypes.StringValue                                                            `tfsdk:"project_id"`
	RateLimits supertypes.SetNestedObjectValueOf[ProjectRateLimitsDataSourceModelRateLimitsItem] `tfsdk:"rate_limits"`
}

type ProjectRateLimitsDataSourceModelRateLimitsItem struct {
	Id                          supertypes.StringValue `tfsdk:"id"`
	Model                       supertypes.StringValue `tfsdk:"model"`
	MaxRequestsPer1Minute       supertypes.Int64Value  `tfsdk:"max_requests_per_1_minute"`
	MaxTokensPer1Minute         supertypes.Int64Value  `tfsdk:"max_tokens_per_1_minute"`
	MaxImagesPer1Minute         supertypes.Int64Value  `tfsdk:"max_images_per_1_minute"`
	MaxAudioMegabytesPer1Minute supertypes.Int64Value  `tfsdk:"max_audio_megabytes_per_1_minute"`
	MaxRequestsPer1Day          supertypes.Int64Value  `tfsdk:"max_requests_per_1_day"`
	Batch1DayMaxInputTokens     supertypes.Int64Value  `tfsdk:"batch_1_day_max_input_tokens"`
}
