// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &ProjectUserRoleAssignmentsDataSource{}

func NewProjectUserRoleAssignmentsDataSource() datasource.DataSource {
	return &ProjectUserRoleAssignmentsDataSource{}
}

type ProjectUserRoleAssignmentsDataSource struct {
	baseDataSource
}

func (d *ProjectUserRoleAssignmentsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_user_role_assignments"
}

func (d *ProjectUserRoleAssignmentsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists the project roles assigned to a user within a project.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project to inspect.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"user_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the user to inspect.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"roles": schema.SetNestedAttribute{
				MarkdownDescription: "List of project roles assigned to the group within the project.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[ProjectUserRoleAssignmentsDataSourceModelRolesItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Identifier for the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Unique name for the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "Description of the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"permissions": schema.SetAttribute{
							MarkdownDescription: "Permissions granted by the role.",
							Computed:            true,
							CustomType:          supertypes.NewSetTypeOf[string](ctx),
						},
						"predefined_role": schema.BoolAttribute{
							MarkdownDescription: "Whether the role is predefined and managed by OpenAI.",
							Computed:            true,
							CustomType:          supertypes.BoolType{},
						},
						"resource_type": schema.StringAttribute{
							MarkdownDescription: "Resource type the role is bound to (for example `api.organization` or `api.project`).",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
		},
	}
}

func (d *ProjectUserRoleAssignmentsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectUserRoleAssignmentsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.AssignedRoleDetails
	params := &apiclient.ListProjectUserRoleAssignmentsParams{
		Limit: ptr.Ptr(int64(100)),
	}

	for {

		httpResp, err := d.client.ListProjectUserRoleAssignmentsWithResponse(ctx, data.ProjectId.ValueString(), data.UserId.ValueString(), params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		if v := getBool(httpResp.JSON200.HasMore); !v {
			break
		}

		if v := getString(httpResp.JSON200.Next); v != "" {
			params.After = &v
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectUserRoleAssignmentsDataSourceModel struct {
	ProjectId supertypes.StringValue                                                                `tfsdk:"project_id"`
	UserId    supertypes.StringValue                                                                `tfsdk:"user_id"`
	Roles     supertypes.SetNestedObjectValueOf[ProjectUserRoleAssignmentsDataSourceModelRolesItem] `tfsdk:"roles"`
}

type ProjectUserRoleAssignmentsDataSourceModelRolesItem struct {
	Id             supertypes.StringValue        `tfsdk:"id"`
	Name           supertypes.StringValue        `tfsdk:"name"`
	Description    supertypes.StringValue        `tfsdk:"description"`
	Permissions    supertypes.SetValueOf[string] `tfsdk:"permissions"`
	PredefinedRole supertypes.BoolValue          `tfsdk:"predefined_role"`
	ResourceType   supertypes.StringValue        `tfsdk:"resource_type"`
}
