// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &ProjectsDataSource{}

func NewProjectsDataSource() datasource.DataSource {
	return &ProjectsDataSource{}
}

type ProjectsDataSource struct {
	baseDataSource
}

func (d *ProjectsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_projects"
}

func (d *ProjectsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List all projects in an organization.",
		Attributes: map[string]schema.Attribute{
			"include_archived": schema.BoolAttribute{
				MarkdownDescription: "Include archived projects. Default is `false`.",
				Optional:            true,
				CustomType:          supertypes.BoolType{},
			},
			"limit": schema.Int64Attribute{
				MarkdownDescription: "Limit the number of projects to return. Default is to return all projects.",
				Optional:            true,
				CustomType:          supertypes.Int64Type{},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"projects": schema.SetNestedAttribute{
				MarkdownDescription: "List of projects.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[ProjectsDataSourceModelProjectsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Project ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the project. This appears in reporting.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "Status `active` or `archived`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"external_key_id": schema.StringAttribute{
							MarkdownDescription: "The ID of the customer-managed encryption key used for Enterprise Key Management (EKM). EKM is only available on certain accounts. Refer to the [EKM (External Keys) in the Management API Article](https://help.openai.com/en/articles/20000953-ekm-external-keys-in-the-management-api).",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the project was created.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"archived_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the project was archived or `null`.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *ProjectsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.Project
	params := &apiclient.ListProjectsParams{
		Limit: ptr.Ptr(int64(100)),
	}

	params.IncludeArchived = data.IncludeArchived.ValueBoolPointer()

	// Set the limit for the API request
	if data.Limit.IsNull() {
		params.Limit = ptr.Ptr(int64(100))
	} else {
		requestLimit := data.Limit.ValueInt64()
		if requestLimit > 100 {
			params.Limit = ptr.Ptr(int64(100))
		} else {
			params.Limit = ptr.Ptr(requestLimit)
		}
	}

done:
	for {

		// Recalculate the limit for each request to ensure we don't exceed the desired limit
		if !data.Limit.IsNull() {
			remainingLimit := data.Limit.ValueInt64() - int64(len(modelInstances))
			if remainingLimit <= 0 {
				break
			}
			if remainingLimit > 100 {
				params.Limit = ptr.Ptr(int64(100))
			} else {
				params.Limit = ptr.Ptr(remainingLimit)
			}
		}

		httpResp, err := d.client.ListProjectsWithResponse(ctx, params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code: %d", httpResp.StatusCode()))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		switch v := any(httpResp.JSON200.HasMore).(type) {
		case bool:
			if !v {
				break done
			}
		case *bool:
			if v == nil || !*v {
				break done
			}
		default:
			panic("unknown type")
		}

		switch v := any(httpResp.JSON200.LastId).(type) {
		case string:
			params.After = &v
		case *string:
			if v == nil {
				params.After = nil
			} else {
				params.After = v
			}
		default:
			panic("unknown type")
		}

		// If limit is set and we have enough projects, break.
		if !data.Limit.IsNull() && len(modelInstances) >= int(data.Limit.ValueInt64()) {
			modelInstances = modelInstances[:data.Limit.ValueInt64()]
			break
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectsDataSourceModel struct {
	IncludeArchived supertypes.BoolValue                                                   `tfsdk:"include_archived"`
	Limit           supertypes.Int64Value                                                  `tfsdk:"limit"`
	Projects        supertypes.SetNestedObjectValueOf[ProjectsDataSourceModelProjectsItem] `tfsdk:"projects"`
}

type ProjectsDataSourceModelProjectsItem struct {
	Id            supertypes.StringValue `tfsdk:"id"`
	Name          supertypes.StringValue `tfsdk:"name"`
	Status        supertypes.StringValue `tfsdk:"status"`
	ExternalKeyId supertypes.StringValue `tfsdk:"external_key_id"`
	CreatedAt     supertypes.Int64Value  `tfsdk:"created_at"`
	ArchivedAt    supertypes.Int64Value  `tfsdk:"archived_at"`
}
