// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	"github.com/samber/lo"
)

var _ datasource.DataSource = &ProjectModelPermissionsDataSource{}

func NewProjectModelPermissionsDataSource() datasource.DataSource {
	return &ProjectModelPermissionsDataSource{}
}

type ProjectModelPermissionsDataSource struct {
	baseDataSource
}

func (d *ProjectModelPermissionsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_model_permissions"
}

func (d *ProjectModelPermissionsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves model access permissions for a project.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project for which model permissions are being set.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"mode": schema.StringAttribute{
				MarkdownDescription: "The model permissions mode to apply. One of `allow_list` or `deny_list`.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"model_ids": schema.SetAttribute{
				MarkdownDescription: "The model IDs included in this permissions policy.",
				Computed:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
		},
	}
}

func (d *ProjectModelPermissionsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectModelPermissionsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := d.client.Admin.Organization.Projects.ModelPermissions.Get(ctx, data.ProjectId.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectModelPermissionsDataSourceModel struct {
	ProjectId supertypes.StringValue        `tfsdk:"project_id"`
	Mode      supertypes.StringValue        `tfsdk:"mode"`
	ModelIds  supertypes.SetValueOf[string] `tfsdk:"model_ids"`
}

func (m *ProjectModelPermissionsDataSourceModel) Fill(ctx context.Context, data openai.ProjectModelPermissions) (diags diag.Diagnostics) {
	m.Mode = supertypes.NewStringValue(string(data.Mode))
	m.ModelIds = supertypes.NewSetValueOfSlice(ctx, lo.Uniq(data.ModelIDs))

	return
}
