// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &UsersDataSource{}

func NewUsersDataSource() datasource.DataSource {
	return &UsersDataSource{}
}

type UsersDataSource struct {
	baseDataSource
}

func (d *UsersDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_users"
}

func (d *UsersDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all of the users in the organization.",
		Attributes: map[string]schema.Attribute{
			"users": schema.SetNestedAttribute{
				MarkdownDescription: "List of users.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[UsersDataSourceModelUsersItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "User ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"email": schema.StringAttribute{
							MarkdownDescription: "The email address of the user.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the user.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"role": schema.StringAttribute{
							MarkdownDescription: "Role `owner` or `reader`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"added_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the user was added.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *UsersDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data UsersDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.User
	params := &apiclient.ListUsersParams{
		Limit: ptr.Ptr(int64(100)),
	}

	for {

		httpResp, err := d.client.ListUsersWithResponse(ctx, params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		if v := getBool(httpResp.JSON200.HasMore); !v {
			break
		}

		if v := getString(httpResp.JSON200.LastId); v != "" {
			params.After = &v
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type UsersDataSourceModel struct {
	Users supertypes.SetNestedObjectValueOf[UsersDataSourceModelUsersItem] `tfsdk:"users"`
}

type UsersDataSourceModelUsersItem struct {
	Id      supertypes.StringValue `tfsdk:"id"`
	Email   supertypes.StringValue `tfsdk:"email"`
	Name    supertypes.StringValue `tfsdk:"name"`
	Role    supertypes.StringValue `tfsdk:"role"`
	AddedAt supertypes.Int64Value  `tfsdk:"added_at"`
}
