// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	"github.com/samber/lo"
)

var _ datasource.DataSource = &UserRoleAssignmentsDataSource{}

func NewUserRoleAssignmentsDataSource() datasource.DataSource {
	return &UserRoleAssignmentsDataSource{}
}

type UserRoleAssignmentsDataSource struct {
	baseDataSource
}

func (d *UserRoleAssignmentsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user_role_assignments"
}

func (d *UserRoleAssignmentsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists the organization roles assigned to a user within the organization.",
		Attributes: map[string]schema.Attribute{
			"user_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the user to inspect.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"roles": schema.SetNestedAttribute{
				MarkdownDescription: "List of organization roles",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[UserRoleAssignmentsDataSourceModelRolesItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Identifier for the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Unique name for the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "Description of the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"permissions": schema.SetAttribute{
							MarkdownDescription: "Permissions granted by the role.",
							Computed:            true,
							CustomType:          supertypes.NewSetTypeOf[string](ctx),
						},
						"predefined_role": schema.BoolAttribute{
							MarkdownDescription: "Whether the role is predefined and managed by OpenAI.",
							Computed:            true,
							CustomType:          supertypes.BoolType{},
						},
						"resource_type": schema.StringAttribute{
							MarkdownDescription: "Resource type the role is bound to (for example `api.organization` or `api.project`).",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
		},
	}
}

func (d *UserRoleAssignmentsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data UserRoleAssignmentsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := openai.AdminOrganizationUserRoleListParams{
		Limit: openai.Int(100),
	}

	iter := d.client.Admin.Organization.Users.Roles.ListAutoPaging(ctx, data.UserId.ValueString(), params)

	var modelInstances []openai.AdminOrganizationUserRoleListResponse
	for iter.Next() {

		modelInstances = append(modelInstances, iter.Current())

	}

	if err := iter.Err(); err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type UserRoleAssignmentsDataSourceModel struct {
	UserId supertypes.StringValue                                                         `tfsdk:"user_id"`
	Roles  supertypes.SetNestedObjectValueOf[UserRoleAssignmentsDataSourceModelRolesItem] `tfsdk:"roles"`
}

func (m *UserRoleAssignmentsDataSourceModel) Fill(ctx context.Context, data []openai.AdminOrganizationUserRoleListResponse) (diags diag.Diagnostics) {
	m.Roles = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, lo.Map(data, func(item openai.AdminOrganizationUserRoleListResponse, _ int) UserRoleAssignmentsDataSourceModelRolesItem {
		var model UserRoleAssignmentsDataSourceModelRolesItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}))

	return
}

type UserRoleAssignmentsDataSourceModelRolesItem struct {
	Id             supertypes.StringValue        `tfsdk:"id"`
	Name           supertypes.StringValue        `tfsdk:"name"`
	Description    supertypes.StringValue        `tfsdk:"description"`
	Permissions    supertypes.SetValueOf[string] `tfsdk:"permissions"`
	PredefinedRole supertypes.BoolValue          `tfsdk:"predefined_role"`
	ResourceType   supertypes.StringValue        `tfsdk:"resource_type"`
}

func (m *UserRoleAssignmentsDataSourceModelRolesItem) Fill(ctx context.Context, data openai.AdminOrganizationUserRoleListResponse) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(string(data.ID))
	m.Name = supertypes.NewStringValue(string(data.Name))
	m.Description = supertypes.NewStringValue(string(data.Description))
	m.Permissions = supertypes.NewSetValueOfSlice(ctx, lo.Uniq(data.Permissions))
	m.PredefinedRole = supertypes.NewBoolValue(bool(data.PredefinedRole))
	m.ResourceType = supertypes.NewStringValue(string(data.ResourceType))

	return
}
