// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &UserDataSource{}

func NewUserDataSource() datasource.DataSource {
	return &UserDataSource{}
}

type UserDataSource struct {
	baseDataSource
}

func (d *UserDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_user"
}

func (d *UserDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves a user by their identifier.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "User ID.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"email": schema.StringAttribute{
				MarkdownDescription: "The email address of the user.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"name": schema.StringAttribute{
				MarkdownDescription: "The name of the user.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"role": schema.StringAttribute{
				MarkdownDescription: "Role `owner` or `reader`.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"added_at": schema.Int64Attribute{
				MarkdownDescription: "The Unix timestamp (in seconds) of when the user was added.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
		},
	}
}

func (d *UserDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data UserDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.client.RetrieveUserWithResponse(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type UserDataSourceModel struct {
	Id      supertypes.StringValue `tfsdk:"id"`
	Email   supertypes.StringValue `tfsdk:"email"`
	Name    supertypes.StringValue `tfsdk:"name"`
	Role    supertypes.StringValue `tfsdk:"role"`
	AddedAt supertypes.Int64Value  `tfsdk:"added_at"`
}
