// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &InviteDataSource{}

func NewInviteDataSource() datasource.DataSource {
	return &InviteDataSource{}
}

type InviteDataSource struct {
	baseDataSource
}

func (d *InviteDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_invite"
}

func (d *InviteDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves an invite.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Invite ID.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"email": schema.StringAttribute{
				MarkdownDescription: "The email address of the individual to whom the invite was sent.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"role": schema.StringAttribute{
				MarkdownDescription: "`owner` or `reader`.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "`accepted`, `expired`, or `pending`.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"invited_at": schema.Int64Attribute{
				MarkdownDescription: "The Unix timestamp (in seconds) of when the invite was sent.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"expires_at": schema.Int64Attribute{
				MarkdownDescription: "The Unix timestamp (in seconds) of when the invite expires.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"accepted_at": schema.Int64Attribute{
				MarkdownDescription: "The Unix timestamp (in seconds) of when the invite was accepted.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
		},
	}
}

func (d *InviteDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data InviteDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := d.client.RetrieveInviteWithResponse(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type InviteDataSourceModel struct {
	Id         supertypes.StringValue `tfsdk:"id"`
	Email      supertypes.StringValue `tfsdk:"email"`
	Role       supertypes.StringValue `tfsdk:"role"`
	Status     supertypes.StringValue `tfsdk:"status"`
	InvitedAt  supertypes.Int64Value  `tfsdk:"invited_at"`
	ExpiresAt  supertypes.Int64Value  `tfsdk:"expires_at"`
	AcceptedAt supertypes.Int64Value  `tfsdk:"accepted_at"`
}
