// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	"github.com/samber/lo"
)

var _ datasource.DataSource = &ProjectRateLimitsDataSource{}

func NewProjectRateLimitsDataSource() datasource.DataSource {
	return &ProjectRateLimitsDataSource{}
}

type ProjectRateLimitsDataSource struct {
	baseDataSource
}

func (d *ProjectRateLimitsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_rate_limits"
}

func (d *ProjectRateLimitsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Returns the rate limits per model for a project.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"rate_limits": schema.SetNestedAttribute{
				MarkdownDescription: "List of rate limits.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[ProjectRateLimitsDataSourceModelRateLimitsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "The rate limit identifier.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"model": schema.StringAttribute{
							MarkdownDescription: "The model this rate limit applies to.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"max_requests_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum requests per minute.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_tokens_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum tokens per minute.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_images_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum images per minute. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_audio_megabytes_per_1_minute": schema.Int64Attribute{
							MarkdownDescription: "The maximum audio megabytes per minute. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"max_requests_per_1_day": schema.Int64Attribute{
							MarkdownDescription: "The maximum requests per day. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"batch_1_day_max_input_tokens": schema.Int64Attribute{
							MarkdownDescription: "The maximum batch input tokens per day. Only present for relevant models.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *ProjectRateLimitsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectRateLimitsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := openai.AdminOrganizationProjectRateLimitListRateLimitsParams{
		Limit: openai.Int(100),
	}

	iter := d.client.Admin.Organization.Projects.RateLimits.ListRateLimitsAutoPaging(ctx, data.ProjectId.ValueString(), params)

	var modelInstances []openai.ProjectRateLimit
	for iter.Next() {

		modelInstances = append(modelInstances, iter.Current())

	}

	if err := iter.Err(); err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectRateLimitsDataSourceModel struct {
	ProjectId  supertypes.StringValue                                                            `tfsdk:"project_id"`
	RateLimits supertypes.SetNestedObjectValueOf[ProjectRateLimitsDataSourceModelRateLimitsItem] `tfsdk:"rate_limits"`
}

func (m *ProjectRateLimitsDataSourceModel) Fill(ctx context.Context, data []openai.ProjectRateLimit) (diags diag.Diagnostics) {
	m.RateLimits = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, lo.Map(data, func(item openai.ProjectRateLimit, _ int) ProjectRateLimitsDataSourceModelRateLimitsItem {
		var model ProjectRateLimitsDataSourceModelRateLimitsItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}))

	return
}

type ProjectRateLimitsDataSourceModelRateLimitsItem struct {
	Id                          supertypes.StringValue `tfsdk:"id"`
	Model                       supertypes.StringValue `tfsdk:"model"`
	MaxRequestsPer1Minute       supertypes.Int64Value  `tfsdk:"max_requests_per_1_minute"`
	MaxTokensPer1Minute         supertypes.Int64Value  `tfsdk:"max_tokens_per_1_minute"`
	MaxImagesPer1Minute         supertypes.Int64Value  `tfsdk:"max_images_per_1_minute"`
	MaxAudioMegabytesPer1Minute supertypes.Int64Value  `tfsdk:"max_audio_megabytes_per_1_minute"`
	MaxRequestsPer1Day          supertypes.Int64Value  `tfsdk:"max_requests_per_1_day"`
	Batch1DayMaxInputTokens     supertypes.Int64Value  `tfsdk:"batch_1_day_max_input_tokens"`
}

func (m *ProjectRateLimitsDataSourceModelRateLimitsItem) Fill(ctx context.Context, data openai.ProjectRateLimit) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(string(data.ID))
	m.Model = supertypes.NewStringValue(string(data.Model))
	m.MaxRequestsPer1Minute = supertypes.NewInt64Value(int64(data.MaxRequestsPer1Minute))
	m.MaxTokensPer1Minute = supertypes.NewInt64Value(int64(data.MaxTokensPer1Minute))
	m.MaxImagesPer1Minute = (func() supertypes.Int64Value {
		if data.JSON.MaxImagesPer1Minute.Valid() {
			return supertypes.NewInt64Value(int64(data.MaxImagesPer1Minute))
		}
		return supertypes.NewInt64Null()
	}())
	m.MaxAudioMegabytesPer1Minute = (func() supertypes.Int64Value {
		if data.JSON.MaxAudioMegabytesPer1Minute.Valid() {
			return supertypes.NewInt64Value(int64(data.MaxAudioMegabytesPer1Minute))
		}
		return supertypes.NewInt64Null()
	}())
	m.MaxRequestsPer1Day = (func() supertypes.Int64Value {
		if data.JSON.MaxRequestsPer1Day.Valid() {
			return supertypes.NewInt64Value(int64(data.MaxRequestsPer1Day))
		}
		return supertypes.NewInt64Null()
	}())
	m.Batch1DayMaxInputTokens = (func() supertypes.Int64Value {
		if data.JSON.Batch1DayMaxInputTokens.Valid() {
			return supertypes.NewInt64Value(int64(data.Batch1DayMaxInputTokens))
		}
		return supertypes.NewInt64Null()
	}())

	return
}
