// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &SpendLimitDataSource{}

func NewSpendLimitDataSource() datasource.DataSource {
	return &SpendLimitDataSource{}
}

type SpendLimitDataSource struct {
	baseDataSource
}

func (d *SpendLimitDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_spend_limit"
}

func (d *SpendLimitDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves organization spend limit.",
		Attributes: map[string]schema.Attribute{
			"currency": schema.StringAttribute{
				MarkdownDescription: "The currency for the threshold amount. Currently, only `USD` is supported.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"interval": schema.StringAttribute{
				MarkdownDescription: "The time interval for evaluating spend against the threshold. Currently, only `month` is supported.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"threshold_amount": schema.Int64Attribute{
				MarkdownDescription: "The hard spend limit amount, in cents.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"enforcement": schema.SingleNestedAttribute{
				MarkdownDescription: "The current enforcement state of the hard spend limit.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[SpendLimitDataSourceModelEnforcement](ctx),
				Attributes: map[string]schema.Attribute{
					"status": schema.StringAttribute{
						MarkdownDescription: "Whether the hard spend limit is currently enforcing.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
		},
	}
}

func (d *SpendLimitDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data SpendLimitDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := d.client.Admin.Organization.SpendLimit.Get(ctx)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type SpendLimitDataSourceModel struct {
	Currency        supertypes.StringValue                                                     `tfsdk:"currency"`
	Interval        supertypes.StringValue                                                     `tfsdk:"interval"`
	ThresholdAmount supertypes.Int64Value                                                      `tfsdk:"threshold_amount"`
	Enforcement     supertypes.SingleNestedObjectValueOf[SpendLimitDataSourceModelEnforcement] `tfsdk:"enforcement"`
}

func (m *SpendLimitDataSourceModel) Fill(ctx context.Context, data openai.OrganizationSpendLimit) (diags diag.Diagnostics) {
	m.Currency = supertypes.NewStringValue(string(data.Currency))
	m.Interval = supertypes.NewStringValue(string(data.Interval))
	m.ThresholdAmount = supertypes.NewInt64Value(int64(data.ThresholdAmount))
	m.Enforcement = supertypes.NewSingleNestedObjectValueOf(ctx, func() *SpendLimitDataSourceModelEnforcement {
		var model SpendLimitDataSourceModelEnforcement
		diags.Append(model.Fill(ctx, data.Enforcement)...)
		return &model
	}())

	return
}

type SpendLimitDataSourceModelEnforcement struct {
	Status supertypes.StringValue `tfsdk:"status"`
}

func (m *SpendLimitDataSourceModelEnforcement) Fill(ctx context.Context, data openai.OrganizationSpendLimitEnforcement) (diags diag.Diagnostics) {
	m.Status = supertypes.NewStringValue(string(data.Status))

	return
}
