// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &ProjectSpendLimitDataSource{}

func NewProjectSpendLimitDataSource() datasource.DataSource {
	return &ProjectSpendLimitDataSource{}
}

type ProjectSpendLimitDataSource struct {
	baseDataSource
}

func (d *ProjectSpendLimitDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_spend_limit"
}

func (d *ProjectSpendLimitDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Retrieves project spend limit.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"currency": schema.StringAttribute{
				MarkdownDescription: "The currency for the threshold amount. Currently, only `USD` is supported.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"interval": schema.StringAttribute{
				MarkdownDescription: "The time interval for evaluating spend against the threshold. Currently, only `month` is supported.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
			},
			"threshold_amount": schema.Int64Attribute{
				MarkdownDescription: "The hard spend limit amount, in cents.",
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"enforcement": schema.SingleNestedAttribute{
				MarkdownDescription: "The current enforcement state of the hard spend limit.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[ProjectSpendLimitDataSourceModelEnforcement](ctx),
				Attributes: map[string]schema.Attribute{
					"status": schema.StringAttribute{
						MarkdownDescription: "Whether the hard spend limit is currently enforcing.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
		},
	}
}

func (d *ProjectSpendLimitDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectSpendLimitDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := d.clientV2.Admin.Organization.Projects.SpendLimit.Get(ctx, data.ProjectId.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectSpendLimitDataSourceModel struct {
	ProjectId       supertypes.StringValue                                                            `tfsdk:"project_id"`
	Currency        supertypes.StringValue                                                            `tfsdk:"currency"`
	Interval        supertypes.StringValue                                                            `tfsdk:"interval"`
	ThresholdAmount supertypes.Int64Value                                                             `tfsdk:"threshold_amount"`
	Enforcement     supertypes.SingleNestedObjectValueOf[ProjectSpendLimitDataSourceModelEnforcement] `tfsdk:"enforcement"`
}

type ProjectSpendLimitDataSourceModelEnforcement struct {
	Status supertypes.StringValue `tfsdk:"status"`
}
