// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	"github.com/samber/lo"
)

var _ datasource.DataSource = &ProjectsDataSource{}

func NewProjectsDataSource() datasource.DataSource {
	return &ProjectsDataSource{}
}

type ProjectsDataSource struct {
	baseDataSource
}

func (d *ProjectsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_projects"
}

func (d *ProjectsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "List all projects in an organization.",
		Attributes: map[string]schema.Attribute{
			"include_archived": schema.BoolAttribute{
				MarkdownDescription: "Include archived projects. Default is `false`.",
				Optional:            true,
				CustomType:          supertypes.BoolType{},
			},
			"limit": schema.Int64Attribute{
				MarkdownDescription: "Limit the number of projects to return. Default is to return all projects.",
				Optional:            true,
				CustomType:          supertypes.Int64Type{},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"projects": schema.SetNestedAttribute{
				MarkdownDescription: "List of projects.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[ProjectsDataSourceModelProjectsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Project ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the project. This appears in reporting.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "Status `active` or `archived`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"external_key_id": schema.StringAttribute{
							MarkdownDescription: "The ID of the customer-managed encryption key used for Enterprise Key Management (EKM). EKM is only available on certain accounts. Refer to the [EKM (External Keys) in the Management API Article](https://help.openai.com/en/articles/20000953-ekm-external-keys-in-the-management-api).",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the project was created.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"archived_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the project was archived or `null`.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *ProjectsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data ProjectsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := openai.AdminOrganizationProjectListParams{
		Limit: openai.Int(100),
	}

	if data.IncludeArchived.IsKnown() {
		params.IncludeArchived = openai.Bool(data.IncludeArchived.ValueBool())
	}

	// Set the limit for the API request
	if data.Limit.IsKnown() {
		requestLimit := data.Limit.ValueInt64()
		if requestLimit > 100 {
			params.Limit = openai.Int(100)
		} else {
			params.Limit = openai.Int(requestLimit)
		}
	} else {
		params.Limit = openai.Int(100)
	}

	iter := d.client.Admin.Organization.Projects.ListAutoPaging(ctx, params)

	var modelInstances []openai.Project
	for iter.Next() {

		modelInstances = append(modelInstances, iter.Current())

		// If limit is set and we have enough projects, break.
		if data.Limit.IsKnown() && len(modelInstances) >= int(data.Limit.ValueInt64()) {
			modelInstances = modelInstances[:data.Limit.ValueInt64()]
			break
		}

	}

	if err := iter.Err(); err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type ProjectsDataSourceModel struct {
	IncludeArchived supertypes.BoolValue                                                   `tfsdk:"include_archived"`
	Limit           supertypes.Int64Value                                                  `tfsdk:"limit"`
	Projects        supertypes.SetNestedObjectValueOf[ProjectsDataSourceModelProjectsItem] `tfsdk:"projects"`
}

func (m *ProjectsDataSourceModel) Fill(ctx context.Context, data []openai.Project) (diags diag.Diagnostics) {
	m.Projects = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, lo.Map(data, func(item openai.Project, _ int) ProjectsDataSourceModelProjectsItem {
		var model ProjectsDataSourceModelProjectsItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}))

	return
}

type ProjectsDataSourceModelProjectsItem struct {
	Id            supertypes.StringValue `tfsdk:"id"`
	Name          supertypes.StringValue `tfsdk:"name"`
	Status        supertypes.StringValue `tfsdk:"status"`
	ExternalKeyId supertypes.StringValue `tfsdk:"external_key_id"`
	CreatedAt     supertypes.Int64Value  `tfsdk:"created_at"`
	ArchivedAt    supertypes.Int64Value  `tfsdk:"archived_at"`
}

func (m *ProjectsDataSourceModelProjectsItem) Fill(ctx context.Context, data openai.Project) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(string(data.ID))
	m.Name = supertypes.NewStringValue(string(data.Name))
	m.Status = supertypes.NewStringValue(string(data.Status))
	m.ExternalKeyId = (func() supertypes.StringValue {
		if data.JSON.ExternalKeyID.Valid() {
			return supertypes.NewStringValue(string(data.ExternalKeyID))
		}
		return supertypes.NewStringNull()
	}())
	m.CreatedAt = supertypes.NewInt64Value(int64(data.CreatedAt))
	m.ArchivedAt = (func() supertypes.Int64Value {
		if data.JSON.ArchivedAt.Valid() {
			return supertypes.NewInt64Value(int64(data.ArchivedAt))
		}
		return supertypes.NewInt64Null()
	}())

	return
}
