// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	"github.com/samber/lo"
)

var _ datasource.DataSource = &InvitesDataSource{}

func NewInvitesDataSource() datasource.DataSource {
	return &InvitesDataSource{}
}

type InvitesDataSource struct {
	baseDataSource
}

func (d *InvitesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_invites"
}

func (d *InvitesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all of the invites in the organization.",
		Attributes: map[string]schema.Attribute{
			"invites": schema.SetNestedAttribute{
				MarkdownDescription: "List of invites.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[InvitesDataSourceModelInvitesItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Invite ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"email": schema.StringAttribute{
							MarkdownDescription: "The email address of the individual to whom the invite was sent.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"role": schema.StringAttribute{
							MarkdownDescription: "`owner` or `reader`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "`accepted`, `expired`, or `pending`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the invite was sent.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"expires_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the invite expires.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"accepted_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the invite was accepted.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *InvitesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data InvitesDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := openai.AdminOrganizationInviteListParams{
		Limit: openai.Int(100),
	}

	iter := d.client.Admin.Organization.Invites.ListAutoPaging(ctx, params)

	var modelInstances []openai.Invite
	for iter.Next() {

		modelInstances = append(modelInstances, iter.Current())

	}

	if err := iter.Err(); err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type InvitesDataSourceModel struct {
	Invites supertypes.SetNestedObjectValueOf[InvitesDataSourceModelInvitesItem] `tfsdk:"invites"`
}

func (m *InvitesDataSourceModel) Fill(ctx context.Context, data []openai.Invite) (diags diag.Diagnostics) {
	m.Invites = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, lo.Map(data, func(item openai.Invite, _ int) InvitesDataSourceModelInvitesItem {
		var model InvitesDataSourceModelInvitesItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}))

	return
}

type InvitesDataSourceModelInvitesItem struct {
	Id         supertypes.StringValue `tfsdk:"id"`
	Email      supertypes.StringValue `tfsdk:"email"`
	Role       supertypes.StringValue `tfsdk:"role"`
	Status     supertypes.StringValue `tfsdk:"status"`
	CreatedAt  supertypes.Int64Value  `tfsdk:"created_at"`
	ExpiresAt  supertypes.Int64Value  `tfsdk:"expires_at"`
	AcceptedAt supertypes.Int64Value  `tfsdk:"accepted_at"`
}

func (m *InvitesDataSourceModelInvitesItem) Fill(ctx context.Context, data openai.Invite) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(string(data.ID))
	m.Email = supertypes.NewStringValue(string(data.Email))
	m.Role = supertypes.NewStringValue(string(data.Role))
	m.Status = supertypes.NewStringValue(string(data.Status))
	m.CreatedAt = supertypes.NewInt64Value(int64(data.CreatedAt))
	m.ExpiresAt = (func() supertypes.Int64Value {
		if data.JSON.ExpiresAt.Valid() {
			return supertypes.NewInt64Value(int64(data.ExpiresAt))
		}
		return supertypes.NewInt64Null()
	}())
	m.AcceptedAt = (func() supertypes.Int64Value {
		if data.JSON.AcceptedAt.Valid() {
			return supertypes.NewInt64Value(int64(data.AcceptedAt))
		}
		return supertypes.NewInt64Null()
	}())

	return
}
