// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &OrganizationRolesDataSource{}

func NewOrganizationRolesDataSource() datasource.DataSource {
	return &OrganizationRolesDataSource{}
}

type OrganizationRolesDataSource struct {
	baseDataSource
}

func (d *OrganizationRolesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_organization_roles"
}

func (d *OrganizationRolesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists the roles configured for the organization.",
		Attributes: map[string]schema.Attribute{
			"roles": schema.SetNestedAttribute{
				MarkdownDescription: "List of roles.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[OrganizationRolesDataSourceModelRolesItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Identifier for the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Unique name for the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"description": schema.StringAttribute{
							MarkdownDescription: "Description of the role.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"permissions": schema.SetAttribute{
							MarkdownDescription: "Permissions granted by the role.",
							Computed:            true,
							CustomType:          supertypes.NewSetTypeOf[string](ctx),
						},
						"predefined_role": schema.BoolAttribute{
							MarkdownDescription: "Whether the role is predefined and managed by OpenAI.",
							Computed:            true,
							CustomType:          supertypes.BoolType{},
						},
						"resource_type": schema.StringAttribute{
							MarkdownDescription: "Resource type the role is bound to (for example `api.organization` or `api.project`).",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
		},
	}
}

func (d *OrganizationRolesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data OrganizationRolesDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.Role
	params := &apiclient.ListRolesParams{
		Limit: ptr.Ptr(int64(100)),
	}

done:
	for {

		httpResp, err := d.client.ListRolesWithResponse(ctx, params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code: %d", httpResp.StatusCode()))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		switch v := any(httpResp.JSON200.HasMore).(type) {
		case bool:
			if !v {
				break done
			}
		case *bool:
			if v == nil || !*v {
				break done
			}
		default:
			panic("unknown type")
		}

		switch v := any(httpResp.JSON200.Next).(type) {
		case string:
			params.After = &v
		case *string:
			if v == nil {
				params.After = nil
			} else {
				params.After = v
			}
		default:
			panic("unknown type")
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type OrganizationRolesDataSourceModel struct {
	Roles supertypes.SetNestedObjectValueOf[OrganizationRolesDataSourceModelRolesItem] `tfsdk:"roles"`
}

type OrganizationRolesDataSourceModelRolesItem struct {
	Id             supertypes.StringValue        `tfsdk:"id"`
	Name           supertypes.StringValue        `tfsdk:"name"`
	Description    supertypes.StringValue        `tfsdk:"description"`
	Permissions    supertypes.SetValueOf[string] `tfsdk:"permissions"`
	PredefinedRole supertypes.BoolValue          `tfsdk:"predefined_role"`
	ResourceType   supertypes.StringValue        `tfsdk:"resource_type"`
}
