// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &GroupsDataSource{}

func NewGroupsDataSource() datasource.DataSource {
	return &GroupsDataSource{}
}

type GroupsDataSource struct {
	baseDataSource
}

func (d *GroupsDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_groups"
}

func (d *GroupsDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all groups in the organization.",
		Attributes: map[string]schema.Attribute{
			"groups": schema.SetNestedAttribute{
				MarkdownDescription: "List of groups.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[GroupsDataSourceModelGroupsItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Identifier for the group.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "Human readable name for the group.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"is_scim_managed": schema.BoolAttribute{
							MarkdownDescription: "Whether the group is managed through SCIM.",
							Computed:            true,
							CustomType:          supertypes.BoolType{},
						},
						"created_at": schema.Int64Attribute{
							MarkdownDescription: "Unix timestamp (in seconds) when the group was created.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *GroupsDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data GroupsDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.GroupResponse
	params := &apiclient.ListGroupsParams{
		Limit: ptr.Ptr(int64(100)),
	}

	for {

		httpResp, err := d.client.ListGroupsWithResponse(ctx, params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		if v := getBool(httpResp.JSON200.HasMore); !v {
			break
		}

		if v := getString(httpResp.JSON200.Next); v != "" {
			params.After = &v
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type GroupsDataSourceModel struct {
	Groups supertypes.SetNestedObjectValueOf[GroupsDataSourceModelGroupsItem] `tfsdk:"groups"`
}

type GroupsDataSourceModelGroupsItem struct {
	Id            supertypes.StringValue `tfsdk:"id"`
	Name          supertypes.StringValue `tfsdk:"name"`
	IsScimManaged supertypes.BoolValue   `tfsdk:"is_scim_managed"`
	CreatedAt     supertypes.Int64Value  `tfsdk:"created_at"`
}
