// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/go-utils/ptr"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &InvitesDataSource{}

func NewInvitesDataSource() datasource.DataSource {
	return &InvitesDataSource{}
}

type InvitesDataSource struct {
	baseDataSource
}

func (d *InvitesDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_invites"
}

func (d *InvitesDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists all of the invites in the organization.",
		Attributes: map[string]schema.Attribute{
			"invites": schema.SetNestedAttribute{
				MarkdownDescription: "List of invites.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[InvitesDataSourceModelInvitesItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "Invite ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"email": schema.StringAttribute{
							MarkdownDescription: "The email address of the individual to whom the invite was sent.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"role": schema.StringAttribute{
							MarkdownDescription: "`owner` or `reader`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"status": schema.StringAttribute{
							MarkdownDescription: "`accepted`, `expired`, or `pending`.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"invited_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the invite was sent.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"expires_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the invite expires.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
						"accepted_at": schema.Int64Attribute{
							MarkdownDescription: "The Unix timestamp (in seconds) of when the invite was accepted.",
							Computed:            true,
							CustomType:          supertypes.Int64Type{},
						},
					},
				},
			},
		},
	}
}

func (d *InvitesDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data InvitesDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.Invite
	params := &apiclient.ListInvitesParams{
		Limit: ptr.Ptr(int64(100)),
	}

	for {

		httpResp, err := d.client.ListInvitesWithResponse(ctx, params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code: %d", httpResp.StatusCode()))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		if v := getBool(httpResp.JSON200.HasMore); !v {
			break
		}

		if v := getString(httpResp.JSON200.LastId); v != "" {
			params.After = &v
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type InvitesDataSourceModel struct {
	Invites supertypes.SetNestedObjectValueOf[InvitesDataSourceModelInvitesItem] `tfsdk:"invites"`
}

type InvitesDataSourceModelInvitesItem struct {
	Id         supertypes.StringValue `tfsdk:"id"`
	Email      supertypes.StringValue `tfsdk:"email"`
	Role       supertypes.StringValue `tfsdk:"role"`
	Status     supertypes.StringValue `tfsdk:"status"`
	InvitedAt  supertypes.Int64Value  `tfsdk:"invited_at"`
	ExpiresAt  supertypes.Int64Value  `tfsdk:"expires_at"`
	AcceptedAt supertypes.Int64Value  `tfsdk:"accepted_at"`
}
