// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ datasource.DataSource = &GroupUsersDataSource{}

func NewGroupUsersDataSource() datasource.DataSource {
	return &GroupUsersDataSource{}
}

type GroupUsersDataSource struct {
	baseDataSource
}

func (d *GroupUsersDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_group_users"
}

func (d *GroupUsersDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists the users assigned to a group.",
		Attributes: map[string]schema.Attribute{
			"group_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the group to update.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"users": schema.SetNestedAttribute{
				MarkdownDescription: "List of users.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[GroupUsersDataSourceModelUsersItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "User ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"email": schema.StringAttribute{
							MarkdownDescription: "The email address of the user.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the user.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
		},
	}
}

func (d *GroupUsersDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data GroupUsersDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var modelInstances []apiclient.GroupUser
	params := &apiclient.ListGroupUsersParams{
		Limit: new(int64(100)),
	}

	for {

		httpResp, err := d.client.ListGroupUsersWithResponse(ctx, data.GroupId.ValueString(), params)
		if err != nil {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
			return
		} else if httpResp.StatusCode() != http.StatusOK {
			resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
			return
		} else if httpResp.JSON200 == nil {
			resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
			return
		}

		modelInstances = append(modelInstances, httpResp.JSON200.Data...)

		if v := getBool(httpResp.JSON200.HasMore); !v {
			break
		}

		if v := getString(httpResp.JSON200.Next); v != "" {
			params.After = &v
		}

	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type GroupUsersDataSourceModel struct {
	GroupId supertypes.StringValue                                                `tfsdk:"group_id"`
	Users   supertypes.SetNestedObjectValueOf[GroupUsersDataSourceModelUsersItem] `tfsdk:"users"`
}

type GroupUsersDataSourceModelUsersItem struct {
	Id      supertypes.StringValue `tfsdk:"id"`
	Email   supertypes.StringValue `tfsdk:"email"`
	Name    supertypes.StringValue `tfsdk:"name"`
	Role    supertypes.StringValue `tfsdk:"role"`
	AddedAt supertypes.Int64Value  `tfsdk:"added_at"`
}
