// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/datasource/schema"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
	"github.com/samber/lo"
)

var _ datasource.DataSource = &GroupUsersDataSource{}

func NewGroupUsersDataSource() datasource.DataSource {
	return &GroupUsersDataSource{}
}

type GroupUsersDataSource struct {
	baseDataSource
}

func (d *GroupUsersDataSource) Metadata(ctx context.Context, req datasource.MetadataRequest, resp *datasource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_group_users"
}

func (d *GroupUsersDataSource) Schema(ctx context.Context, req datasource.SchemaRequest, resp *datasource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Lists the users assigned to a group.",
		Attributes: map[string]schema.Attribute{
			"group_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the group to update.",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"users": schema.SetNestedAttribute{
				MarkdownDescription: "List of users.",
				Computed:            true,
				CustomType:          supertypes.NewSetNestedObjectTypeOf[GroupUsersDataSourceModelUsersItem](ctx),
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"id": schema.StringAttribute{
							MarkdownDescription: "User ID.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"email": schema.StringAttribute{
							MarkdownDescription: "The email address of the user.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
						"name": schema.StringAttribute{
							MarkdownDescription: "The name of the user.",
							Computed:            true,
							CustomType:          supertypes.StringType{},
						},
					},
				},
			},
		},
	}
}

func (d *GroupUsersDataSource) Read(ctx context.Context, req datasource.ReadRequest, resp *datasource.ReadResponse) {
	var data GroupUsersDataSourceModel

	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := openai.AdminOrganizationGroupUserListParams{
		Limit: openai.Int(100),
	}

	iter := d.client.Admin.Organization.Groups.Users.ListAutoPaging(ctx, data.GroupId.ValueString(), params)

	var modelInstances []openai.OrganizationGroupUser
	for iter.Next() {

		modelInstances = append(modelInstances, iter.Current())

	}

	if err := iter.Err(); err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, modelInstances)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

type GroupUsersDataSourceModel struct {
	GroupId supertypes.StringValue                                                `tfsdk:"group_id"`
	Users   supertypes.SetNestedObjectValueOf[GroupUsersDataSourceModelUsersItem] `tfsdk:"users"`
}

func (m *GroupUsersDataSourceModel) Fill(ctx context.Context, data []openai.OrganizationGroupUser) (diags diag.Diagnostics) {
	m.Users = supertypes.NewSetNestedObjectValueOfValueSlice(ctx, lo.Map(data, func(item openai.OrganizationGroupUser, _ int) GroupUsersDataSourceModelUsersItem {
		var model GroupUsersDataSourceModelUsersItem
		diags.Append(model.Fill(ctx, item)...)
		return model
	}))

	return
}

type GroupUsersDataSourceModelUsersItem struct {
	Id    supertypes.StringValue `tfsdk:"id"`
	Email supertypes.StringValue `tfsdk:"email"`
	Name  supertypes.StringValue `tfsdk:"name"`
}

func (m *GroupUsersDataSourceModelUsersItem) Fill(ctx context.Context, data openai.OrganizationGroupUser) (diags diag.Diagnostics) {
	m.Id = supertypes.NewStringValue(string(data.ID))
	m.Email = supertypes.NewStringValue(string(data.Email))
	m.Name = supertypes.NewStringValue(string(data.Name))

	return
}
