// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func (p *OpenAIProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewAdminApiKeyResource,
		NewDataRetentionResource,
		NewGroupResource,
		NewGroupRoleAssignmentResource,
		NewGroupUserResource,
		NewInviteResource,
		NewOrganizationRoleResource,
		NewProjectResource,
		NewProjectGroupRoleAssignmentResource,
		NewProjectModelPermissionsResource,
		NewProjectRateLimitResource,
		NewProjectRoleResource,
		NewProjectServiceAccountResource,
		NewProjectSpendAlertResource,
		NewProjectSpendLimitResource,
		NewProjectUserResource,
		NewProjectUserRoleAssignmentResource,
		NewSpendAlertResource,
		NewSpendLimitResource,
		NewUserRoleResource,
		NewUserRoleAssignmentResource,
	}
}

func (p *OpenAIProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewGroupRoleAssignmentsDataSource,
		NewGroupUsersDataSource,
		NewGroupsDataSource,
		NewInviteDataSource,
		NewInvitesDataSource,
		NewOrganizationRolesDataSource,
		NewProjectDataSource,
		NewProjectGroupRoleAssignmentsDataSource,
		NewProjectModelPermissionsDataSource,
		NewProjectRateLimitsDataSource,
		NewProjectRolesDataSource,
		NewProjectSpendLimitDataSource,
		NewProjectUserRoleAssignmentsDataSource,
		NewProjectsDataSource,
		NewSpendLimitDataSource,
		NewUserDataSource,
		NewUserRoleAssignmentsDataSource,
		NewUsersDataSource,
	}
}
