// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/datasource"
	"github.com/hashicorp/terraform-plugin-framework/resource"
)

func (p *OpenAIProvider) Resources(ctx context.Context) []func() resource.Resource {
	return []func() resource.Resource{
		NewAdminApiKeyResource,
		NewGroupResource,
		NewInviteResource,
		NewOrganizationRoleResource,
		NewProjectResource,
		NewProjectRateLimitResource,
		NewProjectRoleResource,
		NewProjectServiceAccountResource,
		NewProjectUserResource,
		NewUserRoleResource,
	}
}

func (p *OpenAIProvider) DataSources(ctx context.Context) []func() datasource.DataSource {
	return []func() datasource.DataSource{
		NewGroupsDataSource,
		NewInviteDataSource,
		NewInvitesDataSource,
		NewOrganizationRolesDataSource,
		NewProjectDataSource,
		NewProjectRateLimitsDataSource,
		NewProjectRolesDataSource,
		NewProjectsDataSource,
		NewUserDataSource,
		NewUsersDataSource,
	}
}
