// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/avast/retry-go"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/jianyuan/terraform-provider-openai/internal/apiclient"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &SpendAlertResource{}
var _ resource.ResourceWithImportState = &SpendAlertResource{}

func NewSpendAlertResource() resource.Resource {
	return &SpendAlertResource{}
}

type SpendAlertResource struct {
	baseResource
}

func (r *SpendAlertResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_spend_alert"
}

func (r *SpendAlertResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Creates an organization spend alert.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Spend alert ID.",
				Computed:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"currency": schema.StringAttribute{
				MarkdownDescription: "The currency for the threshold amount (e.g. `USD`).",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"interval": schema.StringAttribute{
				MarkdownDescription: "The interval for the spend alert (e.g. `month`).",
				Required:            true,
				CustomType:          supertypes.StringType{},
			},
			"notification_channel": schema.SingleNestedAttribute{
				MarkdownDescription: "Email notification settings for a spend alert.",
				Required:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[SpendAlertResourceModelNotificationChannel](ctx),
				Attributes: map[string]schema.Attribute{
					"type": schema.StringAttribute{
						MarkdownDescription: "The notification channel type. Currently only `email` is supported.",
						Required:            true,
						CustomType:          supertypes.StringType{},
						Validators: []validator.String{
							stringvalidator.OneOf("email"),
						},
					},
					"recipients": schema.SetAttribute{
						MarkdownDescription: "Email addresses that receive the spend alert notification.",
						Required:            true,
						CustomType:          supertypes.NewSetTypeOf[string](ctx),
					},
					"subject_prefix": schema.StringAttribute{
						MarkdownDescription: "Optional subject prefix for alert emails.",
						Optional:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
			"threshold_amount": schema.Int64Attribute{
				MarkdownDescription: "The alert threshold amount, in cents.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
			},
		},
	}
}

func (r *SpendAlertResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SpendAlertResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.client.CreateOrganizationSpendAlertWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpendAlertResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SpendAlertResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	var responseData *apiclient.OrganizationSpendAlert

	err := retry.Do(
		func() error {
			params := &apiclient.ListOrganizationSpendAlertsParams{
				Limit: new(int64(100)),
			}

			for {
				httpResp, err := r.client.ListOrganizationSpendAlertsWithResponse(ctx, params)
				if err != nil {
					return fmt.Errorf("Unable to read, got error: %s", err)
				} else if httpResp.StatusCode() != http.StatusOK {
					return fmt.Errorf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body))
				} else if httpResp.JSON200 == nil {
					return fmt.Errorf("Unable to read, got empty response body")
				}

				for _, responseDataItem := range httpResp.JSON200.Data {
					if r.resourceMatch(data, responseDataItem) {
						responseData = &responseDataItem
						break
					}
				}

				if v := getBool(httpResp.JSON200.HasMore); !v {
					break
				}

				if v := getString(httpResp.JSON200.LastId); v != "" {
					params.After = &v
				}
			}

			if responseData == nil {
				return fmt.Errorf("Unable to read, could not find resource in the list")
			}

			return nil
		},
		retry.Delay(5*time.Second),
	)

	if err != nil {
		resp.Diagnostics.AddError("Client Error", err.Error())
		return
	}

	if responseData == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpendAlertResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SpendAlertResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.client.UpdateOrganizationSpendAlertWithResponse(ctx, data.Id.ValueString(), body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpendAlertResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data SpendAlertResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.client.DeleteOrganizationSpendAlertWithResponse(ctx, data.Id.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	} else if httpResp.StatusCode() == http.StatusNotFound {
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	}
}

func (r *SpendAlertResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}

type SpendAlertResourceModel struct {
	Id                  supertypes.StringValue                                                           `tfsdk:"id"`
	Currency            supertypes.StringValue                                                           `tfsdk:"currency"`
	Interval            supertypes.StringValue                                                           `tfsdk:"interval"`
	NotificationChannel supertypes.SingleNestedObjectValueOf[SpendAlertResourceModelNotificationChannel] `tfsdk:"notification_channel"`
	ThresholdAmount     supertypes.Int64Value                                                            `tfsdk:"threshold_amount"`
}

type SpendAlertResourceModelNotificationChannel struct {
	Type          supertypes.StringValue        `tfsdk:"type"`
	Recipients    supertypes.SetValueOf[string] `tfsdk:"recipients"`
	SubjectPrefix supertypes.StringValue        `tfsdk:"subject_prefix"`
}
