// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &ProjectRateLimitResource{}

func NewProjectRateLimitResource() resource.Resource {
	return &ProjectRateLimitResource{}
}

type ProjectRateLimitResource struct {
	baseResource
}

func (r *ProjectRateLimitResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_rate_limit"
}

func (r *ProjectRateLimitResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manage rate limits per model for projects. Rate limits may be configured to be equal to or lower than the organization's rate limits.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"rate_limit_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the rate limit. This is typically in the format `rl-<model>`.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"max_requests_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "The maximum requests per minute.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"max_tokens_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "The maximum tokens per minute.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"max_images_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "The maximum images per minute. Only relevant for certain models.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"max_audio_megabytes_per_1_minute": schema.Int64Attribute{
				MarkdownDescription: "The maximum audio megabytes per minute. Only relevant for certain models.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"max_requests_per_1_day": schema.Int64Attribute{
				MarkdownDescription: "The maximum requests per day. Only relevant for certain models.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
			"batch_1_day_max_input_tokens": schema.Int64Attribute{
				MarkdownDescription: "The maximum batch input tokens per day. Only relevant for certain models.",
				Optional:            true,
				Computed:            true,
				CustomType:          supertypes.Int64Type{},
			},
		},
	}
}

func (r *ProjectRateLimitResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ProjectRateLimitResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := r.client.Admin.Organization.Projects.RateLimits.UpdateRateLimit(ctx, data.ProjectId.ValueString(), data.RateLimitId.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectRateLimitResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ProjectRateLimitResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	params := openai.AdminOrganizationProjectRateLimitListRateLimitsParams{
		Limit: openai.Int(100),
	}

	var modelInstance *openai.ProjectRateLimit

	iter := r.client.Admin.Organization.Projects.RateLimits.ListRateLimitsAutoPaging(ctx, data.ProjectId.ValueString(), params)
	for iter.Next() {
		currentModelInstance := iter.Current()
		if r.resourceMatch(data, currentModelInstance) {
			modelInstance = new(currentModelInstance)
			break
		}
	}

	if err := iter.Err(); err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectRateLimitResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ProjectRateLimitResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := r.client.Admin.Organization.Projects.RateLimits.UpdateRateLimit(ctx, data.ProjectId.ValueString(), data.RateLimitId.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectRateLimitResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("Not Supported", "Delete is not supported for this resource. Please manually delete the resource.")
}

type ProjectRateLimitResourceModel struct {
	ProjectId                   supertypes.StringValue `tfsdk:"project_id"`
	RateLimitId                 supertypes.StringValue `tfsdk:"rate_limit_id"`
	MaxRequestsPer1Minute       supertypes.Int64Value  `tfsdk:"max_requests_per_1_minute"`
	MaxTokensPer1Minute         supertypes.Int64Value  `tfsdk:"max_tokens_per_1_minute"`
	MaxImagesPer1Minute         supertypes.Int64Value  `tfsdk:"max_images_per_1_minute"`
	MaxAudioMegabytesPer1Minute supertypes.Int64Value  `tfsdk:"max_audio_megabytes_per_1_minute"`
	MaxRequestsPer1Day          supertypes.Int64Value  `tfsdk:"max_requests_per_1_day"`
	Batch1DayMaxInputTokens     supertypes.Int64Value  `tfsdk:"batch_1_day_max_input_tokens"`
}
