// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/openai/openai-go/v3"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &ProjectModelPermissionsResource{}
var _ resource.ResourceWithImportState = &ProjectModelPermissionsResource{}

func NewProjectModelPermissionsResource() resource.Resource {
	return &ProjectModelPermissionsResource{}
}

type ProjectModelPermissionsResource struct {
	baseResource
}

func (r *ProjectModelPermissionsResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_project_model_permissions"
}

func (r *ProjectModelPermissionsResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Updates model access permissions for a project.",
		Attributes: map[string]schema.Attribute{
			"project_id": schema.StringAttribute{
				MarkdownDescription: "The ID of the project for which model permissions are being set.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
			},
			"mode": schema.StringAttribute{
				MarkdownDescription: "The model permissions mode to apply. One of `allow_list` or `deny_list`.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.OneOf("allow_list", "deny_list"),
				},
			},
			"model_ids": schema.SetAttribute{
				MarkdownDescription: "The model IDs included in this permissions policy.",
				Required:            true,
				CustomType:          supertypes.NewSetTypeOf[string](ctx),
			},
		},
	}
}

func (r *ProjectModelPermissionsResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data ProjectModelPermissionsResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getNewParams(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := r.client.Admin.Organization.Projects.ModelPermissions.Update(ctx, data.ProjectId.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectModelPermissionsResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data ProjectModelPermissionsResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := r.client.Admin.Organization.Projects.ModelPermissions.Get(ctx, data.ProjectId.ValueString())
	if err != nil {
		if apiErr, ok := errors.AsType[*openai.Error](err); ok && apiErr.StatusCode == http.StatusNotFound {
			resp.State.RemoveResource(ctx)
			return
		}

		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectModelPermissionsResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data ProjectModelPermissionsResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateParams(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	modelInstance, err := r.client.Admin.Organization.Projects.ModelPermissions.Update(ctx, data.ProjectId.ValueString(), *body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if modelInstance == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *modelInstance)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *ProjectModelPermissionsResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data ProjectModelPermissionsResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	_, err := r.client.Admin.Organization.Projects.ModelPermissions.Delete(ctx, data.ProjectId.ValueString())
	if err != nil {
		if apiErr, ok := errors.AsType[*openai.Error](err); ok && apiErr.StatusCode == http.StatusNotFound {
			return
		}

		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete, got error: %s", err))
		return
	}
}

func (r *ProjectModelPermissionsResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("project_id"), req, resp)
}

type ProjectModelPermissionsResourceModel struct {
	ProjectId supertypes.StringValue        `tfsdk:"project_id"`
	Mode      supertypes.StringValue        `tfsdk:"mode"`
	ModelIds  supertypes.SetValueOf[string] `tfsdk:"model_ids"`
}
