// Code generated by providergen. DO NOT EDIT.
package provider

import (
	"context"
	"fmt"
	"net/http"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	supertypes "github.com/orange-cloudavenue/terraform-plugin-framework-supertypes"
)

var _ resource.Resource = &SpendLimitResource{}

func NewSpendLimitResource() resource.Resource {
	return &SpendLimitResource{}
}

type SpendLimitResource struct {
	baseResource
}

func (r *SpendLimitResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_spend_limit"
}

func (r *SpendLimitResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Updates organization spend limit.",
		Attributes: map[string]schema.Attribute{
			"currency": schema.StringAttribute{
				MarkdownDescription: "The currency for the threshold amount. Currently, only `USD` is supported.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.OneOf("USD"),
				},
			},
			"interval": schema.StringAttribute{
				MarkdownDescription: "The time interval for evaluating spend against the threshold. Currently, only `month` is supported.",
				Required:            true,
				CustomType:          supertypes.StringType{},
				Validators: []validator.String{
					stringvalidator.OneOf("month"),
				},
			},
			"threshold_amount": schema.Int64Attribute{
				MarkdownDescription: "The hard spend limit amount, in cents.",
				Required:            true,
				CustomType:          supertypes.Int64Type{},
				Validators: []validator.Int64{
					int64validator.AtLeast(1),
				},
			},
			"enforcement": schema.SingleNestedAttribute{
				MarkdownDescription: "The current enforcement state of the hard spend limit.",
				Computed:            true,
				CustomType:          supertypes.NewSingleNestedObjectTypeOf[SpendLimitResourceModelEnforcement](ctx),
				Attributes: map[string]schema.Attribute{
					"status": schema.StringAttribute{
						MarkdownDescription: "Whether the hard spend limit is currently enforcing.",
						Computed:            true,
						CustomType:          supertypes.StringType{},
					},
				},
			},
		},
	}
}

func (r *SpendLimitResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data SpendLimitResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getCreateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.client.UpdateOrganizationSpendLimitWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to create, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpendLimitResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data SpendLimitResourceModel

	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.client.RetrieveOrganizationSpendLimitWithResponse(ctx)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, got empty response body")
		return
	}

	responseData := httpResp.JSON200

	if responseData == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to read, could not find resource in the list")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *responseData)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpendLimitResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data SpendLimitResourceModel

	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	body, diags := r.getUpdateJSONRequestBody(ctx, data)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	httpResp, err := r.client.UpdateOrganizationSpendLimitWithResponse(ctx, body)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got error: %s", err))
		return
	} else if httpResp.StatusCode() != http.StatusOK {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update, got status code %d: %s", httpResp.StatusCode(), string(httpResp.Body)))
		return
	} else if httpResp.JSON200 == nil {
		resp.Diagnostics.AddError("Client Error", "Unable to update, got empty response body")
		return
	}

	resp.Diagnostics.Append(data.Fill(ctx, *httpResp.JSON200)...)
	if resp.Diagnostics.HasError() {
		return
	}

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *SpendLimitResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	resp.Diagnostics.AddWarning("Not Supported", "Delete is not supported for this resource. Please manually delete the resource.")
}

type SpendLimitResourceModel struct {
	Currency        supertypes.StringValue                                                   `tfsdk:"currency"`
	Interval        supertypes.StringValue                                                   `tfsdk:"interval"`
	ThresholdAmount supertypes.Int64Value                                                    `tfsdk:"threshold_amount"`
	Enforcement     supertypes.SingleNestedObjectValueOf[SpendLimitResourceModelEnforcement] `tfsdk:"enforcement"`
}

type SpendLimitResourceModelEnforcement struct {
	Status supertypes.StringValue `tfsdk:"status"`
}
